<h3>Розв'язання задачі про призначення</h3>
<p>Фірма отримала замовлення щодо розроблення п'яти програмних продуктів. На фірмі працюють п'ять кваліфікованих програмістів, яким можна доручити виконання цих замовлень. Кожен програміст дав оцінку часу, що йому потрібно відносно розробки програм. Ці оцінки наведені у таблиці.</p>

In [16]:
import pandas as pd
import numpy as np
from scipy.optimize import linear_sum_assignment

df = pd.read_csv('task.csv')
df.set_index("Programmers:", inplace=True)

print(df)

              program1  program2  program3  program4  program5
Programmers:                                                  
Pavlenko            46        59        24        62        67
Ivanchenko          47        56        32        55        70
Sydorchenko         44        52        19        61        60
Zaychenko           47        59        17        64        73
Braytenko           43        65        20        60        75


Данні також можна представити у вигляді матриці

In [17]:
time_matrix = df.to_numpy()
print(time_matrix)

[[46 59 24 62 67]
 [47 56 32 55 70]
 [44 52 19 61 60]
 [47 59 17 64 73]
 [43 65 20 60 75]]


Використаємо угорський алгоритм для визначення оптимального розподілення завдань

In [18]:
row_ind, col_ind = linear_sum_assignment(time_matrix)

assigments = {}
for i, j in zip(row_ind, col_ind):
    assigments[df.index[i]] = df.columns[j]

for programmer, program in  assigments.items():
    print(f'{programmer} is assigned to {program}')

Pavlenko is assigned to program5
Ivanchenko is assigned to program4
Sydorchenko is assigned to program2
Zaychenko is assigned to program3
Braytenko is assigned to program1
